### ISSUE TITLE
Bug : Calcul de MODO auto via l'équipement

### ISSUE THREAD

**Issue by OrnetAndIce** [Nnayl/brigandyne2e-csb-sheets#1]
Salut juste pour transmettre un bug (alors je pense que c'est uniquement pour moi mais enfin je demande au cas ou).
Donc en gros j'ai fais un personnage , j'ai fais un PNJ. Je tente d'attaqué le PNJ avec la fonction d'attaque et de calcul auto en fonction du MODO mais des ERROR apparaisse. 
![image](https://github.com/Nnayl/brigandyne2e-csb-sheets/assets/130864032/e60325da-cb56-4137-be17-4c15f7680fe2)

![image](https://github.com/Nnayl/brigandyne2e-csb-sheets/assets/130864032/9fbaab59-bc8f-435a-beff-1ec63295ab06)

![image](https://github.com/Nnayl/brigandyne2e-csb-sheets/assets/130864032/7877ecf1-3ee6-4548-9544-40fe407859b8)

Et pourtant je sélectionne une cible. 

Merci de votre futur réponse (alors je sais absolument pas comment fonctionne Github donc je sais même pas si je fais bien de report mon problème mdr)

**Comment by Nnayl** [comment]
Salut,

Oui, l'erreur fait suite à la montée de version de CSB en  3.0.
Le module n'est pas encore compatible avec cette version

Corrigé dans la version 1.5.0

**Comment by OrnetAndIce** [comment]
OKKKEY merci de votre réponse
